### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by JuanMPinera** [Project-MONAI/MONAILabel#862] opened 2022-07-05 23:42 UTC
I installed the weekly version and started the server, but when I try to connect from Slicer, it gives me the next error:

![image](https://user-images.githubusercontent.com/26545600/177433972-8d3adbc0-0067-4f71-8229-5d7d02e2d44b.png)

How can I solve this?
Thanks

**Comment by SachidanandAlle** [comment] 2022-07-05 23:54
i see this issue caused by conda env.. we will have a quick fix for this..

**Closed** 2022-07-06 10:29 UTC
