### ISSUE TITLE
Miscellaneous - Generated mask is shown with different origin from the original image

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#211] opened 2021-07-14 16:21 UTC
**Describe the bug**
Slicer shows the automatic label with a different origin. Apparently, it is related to the way ITK interprets the nifty header. From this discussion, it seems nibabel and nifty differ in the way they interpret the nifty header (https://github.com/nipy/nibabel/issues/863)

CC @wyli 

**To Reproduce**
Using the Fusion Challenge dataset MICCAI 2012 (OASIS project) to train highresnet for Brain parcellation.

Fusion Challenge dataset MICCAI 2012: 35 brain MRI scans obtained from the OASIS project. The manual brain segmentations of these images were produced by Neuromorphometrics, Inc. (http://Neuromorphometrics.com/) using the brainCOLOR labeling protocol.

**Expected behavior**
To show the label in the same origin as the original image

**Screenshots**
The workaround for this is to first change the affine of images and labels. Then use MONAI Label to train the model. See the affine changes in the following images

Original Affine:

![original_affine_origin](https://user-images.githubusercontent.com/11991079/125656821-963e91fd-3332-4dd6-9e5c-40d7100456ce.png)

Modified affine:

![modified_origin_affine](https://user-images.githubusercontent.com/11991079/125656815-6e4e32f1-0ad3-419e-9626-77fe2fb31f1a.png)

**Comment by lassoan** [comment] 2021-07-14 17:20
Storing a 3D image does not have to be complicated, only NIFTI has these orientation issues (and a host of other problems). We lost so much time over the years with debugging various NIFTI problems and developing workarounds - this really has to stop. I would recommend to not use NIFTI format and discourage everyone else from using it. It would be hard to convince neuroimaging people to start using something else, but there is no reason for other communities to suffer.

If you have some original data in NIFTI format then you can convert it correctly (using all workarounds that are needed) to NRRD once, and then you won't have issues with inconsistencies related to image orientations, how to interpret the redundant sform/qform fields, what to do with [non-orthogonal image axes](https://github.com/InsightSoftwareConsortium/ITK/issues/1042), [corrupted files](https://github.com/InsightSoftwareConsortium/ITK/issues/2243), and all the other problems (see some of them [here](https://github.com/InsightSoftwareConsortium/ITK/search?p=2&q=nifti&type=issues)).

**Comment by curtislisle** [comment] 2021-07-14 18:10
I have also heard that ITK's NIFTI implementation has some troubles.  I recommend allowing other image formats in MONAILabel. NRRD would be fine with me.   I see a few places in the  MONAILabel code where *.nii and *.nii.gz are the only allowed extensions.  On the ZARR format, recent ITK releases have added support for it.  It is space efficient and supports compression.  If Zarr and NRRD were added as supported formats (ITK handles them), that would provide good alternatives.  Thanks for this consideration.

**Comment by wyli** [comment] 2021-07-14 19:03
I'm looking at this specific issue, I'm wondering if it is possible to set 3D Slicer to use the `sform` in nifti for visualisation? (looks like 3D slicer would only look at the `qform`, but I couldn't find the relevant docs.). That would be an easy way out for this ticket.

**Comment by wyli** [comment] 2021-07-14 19:19
Another workaround in this context is to use tools to modify the original image such as  `fslorient -copyqform2sform 1000_3.nii` to make the sform, qform consistent.

**Comment by curtislisle** [comment] 2021-07-14 19:25
I see from other packages, that `sform` is preferred now over `qform` by the community (see reference from ANTs, a major registrtion package: https://github.com/ANTsX/ANTs/issues/1141 https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F) .  I support the suggestion of making the header consistent through `fslorient` over modifying 3D Slicer.  Slicer fixes need to be done slowly and carefully, as it is currently used in real-time surgical applications.

**Comment by lassoan** [comment] 2021-07-14 19:37
> I'm looking at this specific issue, I'm wondering if it is possible to set 3D Slicer to use the sform in nifti for visualisation? (looks like 3D slicer would only look at the qform, but I couldn't find the relevant docs.). That would be an easy way out for this ticket.

Slicer uses ITK to read images from NIFTI file format, so Slicer does what all other ITK-based applications do (that use the current ITK version).

I don't know what strategy ITK implements exactly now, but it does not really matter, because there is no common agreement in the neuroimaging community about how to use sform/qform in certain situations, so there is no single "correct" solution. To complicate matters further, the behavior changed many times over the past two decades - in different versions of NIFTI format and in different versions of its implementations.

**Comment by wyli** [comment] 2021-07-14 19:58
> Slicer uses ITK to read images from NIFTI file format, so Slicer does what all other ITK-based applications do (that use the current ITK version).
>

I guess that could be true in theory, but in practice that is not correct... ITK-snap loads the image+segmentation properly, with a warning message saying 'header mismatch and the (segmentation) header is ignored'.

**Comment by SachidanandAlle** [comment] 2021-07-16 15:36
> I have also heard that ITK's NIFTI implementation has some troubles. I recommend allowing other image formats in MONAILabel. NRRD would be fine with me. I see a few places in the MONAILabel code where *.nii and *.nii.gz are the only allowed extensions. On the ZARR format, recent ITK releases have added support for it. It is space efficient and supports compression. If Zarr and NRRD were added as supported formats (ITK handles them), that would provide good alternatives. Thanks for this consideration.

monailabel supports other extensions.. simple way to force output to be nrrd is...
in your sample app (go to info.yaml) and add following item in config->infer section

```
config:
  infer:
    device: cuda
    result_extension: .nrrd
```

or you can send it per request in your infer API (in the params json)

**Comment by diazandr3s** [comment] 2021-07-16 15:46
[**LoadImaged**](https://docs.monai.io/en/latest/_modules/monai/transforms/io/array.html#LoadImage) transform in MONAI uses different readers (ITKReader(), NumpyReader(), PILReader(), NibabelReader()).
[Here](https://itk.org/Wiki/ITK/File_Formats) is the list of formats ITKReader supports

**Comment by lassoan** [comment] 2021-07-16 15:52
> ITK-snap loads the image+segmentation properly, with a warning message saying 'header mismatch and the (segmentation) header is ignored' -- while Slicer shows the mismatched image and seg. quietly.

Latest ITK-Snap version was released more than 2 years ago. It is very far from latest ITK.

ITK-Snap complains about header mismatch because it just cannot handle images and segmentations with different geometries (origin, spacing, axis directions, or extents). It is completely valid to use images and segmentations with different geometries (for example, the segmentation may use isotropic spacing and/or smaller spacing than the input images), and rejecting such images/segmentations or ignoring the header information is a not a feature but a limitation of ITK-Snap.

**Comment by lassoan** [comment] 2021-07-16 16:03
> LoadImaged transform in MONAI uses different readers (ITKReader(), NumpyReader(), PILReader(), NibabelReader()).
Here is the list of formats ITKReader supports

Thanks for all the information. It is clear that MONAI supports multiple file formats. The problem is the NIFTI format is overrepresented in MONAI examples and sample data sets and seems to be used by default when a 3D image file format is needed. This may give the false impression to newcomers that it is OK to use NIFTI as a general-purpose 3D image file format.

**Comment by SachidanandAlle** [comment] 2021-09-01 00:04
no more updates on this issue.  closing now.. 
> for e.g. monailabel server supports multiple output extensions (for e.g. nrrd is used for writing output masks to get consumed in ohif)

**Comment by lassoan** [comment] 2021-10-22 01:01
> Should we encourage researchers to convert NIFTI images into NRRD format when using MONAI Label?

I would strongly support this. Nifti is developed for functional MRI image interchange and has several serious issues that make it a bad choice as general-purpose medical image computing file format.

**Closed** 2022-04-14 08:01 UTC
Labels: bug, 0.4.0
